[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-magic-trailing-comma = true
exclude = "hydpy_mpr/data/|hydpy_mpr/testing/iotesting"

[tool.pytest.ini_options]
testpaths = ["hydpy_mpr/testing"]
